smtp:
  server: smtp.example.com
  port: 587
  user: your_email@example.com
  password: YOUR_PASSWORD_HERE

owner:
  username: your_username
  email: your_email
  password: your_password

openai:
  openai_key: OPENAI_API_KEY

google:
  key: GOOGLE_API_KEY
  cx: GOOGLE_CX

bmc:
  key: BMC_API_KEY
